db:
  host: localhost
  port: 5432
  name: BioData_UniProt
  user: usuario
  password: clave

  schema: public

  tables:
    embeddings: sequence_embeddings
    embedding_types: sequence_embedding_type
    sequences: sequence
    proteins: protein
