
aggregation:
  mode: none

missing_embeddings:
  allow_models:
    GeOKG: artifacts/missing_gope.txt

sequencePE:
  enabled: True
  load_from: db
  models:
    ESM: # 34 layers: 0..33
      enabled: False
      layer_index: [ 0 ]
      distance_threshold: 0

    ESM3c: # 36 layers: 0..35
      enabled: True
      layer_index: [ 0 ]

    Ankh3-Large: # 49 layers: 0..48
      enabled: True
      layer_index: [ 0 ]

    Prot-T5: # 25 layers: 0..24
      enabled: False
      layer_index: [ 0 ]

    Prost-T5: # 25 layers: 0..24 (same backbone as Prot-T5)
      enabled: True
      layer_index: [ 0 ]

GOPE:
  enabled: True
  load_from: file
  file_info:
    folder: /home/alexdoro/DATASETS/mf_proteins/mfp_balanced
    file_name_BP: bp_protein_embeddings_20260302_171152.csv
    file_name_MF: mf_protein_embeddings_20260302_171152.csv
    file_name_CC: cc_protein_embeddings_20260302_171152.csv
    accession_column: uniprot_id
    embedding_column: embedding
  models:
    GeOKG:
      enabled: True

structurePE:
  enabled: False
  load_from: file
  file_info:
    folder: /home/alexdoro/DATASETS/mf_proteins/3di_embeddings
    file_name: 3di_embeddings.csv
  models:
    3di: 
      enabled: False
      layer_index: [ 0 ]
