  models:
    ESM: # 34 layers: 0..33
      enabled: True
      batch_size: 1
      layer_index: [ 0, 5, 11, 17 ]
      distance_threshold: 0

    ESM3c: # 36 layers: 0..35
      enabled: True
      batch_size: 1
      layer_index: [ 0, 5, 11, 17 ]
      distance_threshold: 0

    Ankh3-Large: # 49 layers: 0..48
      enabled: True
      batch_size: 1
      layer_index: [ 0, 8, 16, 24 ]
      distance_threshold: 0

    Prot-T5: # 25 layers: 0..24
      enabled: True
      batch_size: 1
      layer_index: [ 0, 4, 8, 12 ]
      distance_threshold: 0

    Prost-T5: # 25 layers: 0..24 (same backbone as Prot-T5)
      enabled: True
      batch_size: 1
      layer_index: [ 0, 4, 8, 12 ]
      distance_threshold: 0
