paths:
  base_dir: /Users/alexdominguezrodriguez/Documents/GitHub/CABD/mfp-dataset-designer/data
  input_dir: /Users/alexdominguezrodriguez/Documents/GitHub/CABD/mfp-dataset-designer/data/input
  intermediate_dir: .experiments/runs/20260803_0304_a68aa0bb
  output_dir: .experiments/runs/20260803_0304_a68aa0bb
  obo_path: /Users/alexdominguezrodriguez/Documents/GitHub/CABD/mfp-dataset-designer/go-basic.obo
database:
  enabled: false
  dbname: BioData
  user: usuario
  password: clave
  host: localhost
  port: 5432
input_files:
  target_csv:
    path: /Users/alexdominguezrodriguez/Documents/GitHub/CABD/mfp-dataset-designer/data/input/target/proteinas_mf_go_terms.csv
    protein_id_column: protein_id
    sequence_column: sequence
    go_terms_column: go_terms
    organism:
      organism_column: organism
      force_organism: null
  blacklist_csv:
    path: /Users/alexdominguezrodriguez/Documents/GitHub/CABD/mfp-dataset-designer/data/input/blacklist_proteins.csv
    protein_id_column: protein_id
    sequence_column: sequence
    go_terms_column: go_terms
  non_target_csvs:
  - path:
    - /Users/alexdominguezrodriguez/Documents/GitHub/CABD/mfp-dataset-designer/data/input/non_target/BioData_ARABIDOPSIS.csv
    - /Users/alexdominguezrodriguez/Documents/GitHub/CABD/mfp-dataset-designer/data/input/non_target/BioData_ECOLI.csv
    - /Users/alexdominguezrodriguez/Documents/GitHub/CABD/mfp-dataset-designer/data/input/non_target/BioData_MOUSE.csv
    - /Users/alexdominguezrodriguez/Documents/GitHub/CABD/mfp-dataset-designer/data/input/non_target/BioData_YEAST.csv
    protein_id_column: protein_id
    sequence_column: seq
    go_terms_column: go_terms
    organism:
      organism_column: null
      force_organism:
      - Arabidopsis thaliana (Mouse-ear cress).
      - Escherichia coli (strain K12).
      - Mus musculus (Mouse).
      - Saccharomyces cerevisiae (Baker's yeast).
  protein_id_column: protein_id
  sequence_column: sequence
  go_terms_column: go_terms
filters:
  organism_filter:
  - Arabidopsis thaliana (Mouse-ear cress).
  - Escherichia coli (strain K12).
  - Mus musculus (Mouse).
  - Saccharomyces cerevisiae (Baker's yeast).
  len_variance: 0.05
  max_sequence_identity: 0.95
  min_candidates_per_mf: 5
assignment:
  n_assignments_per_mf: 100
  poisson_alpha: 1.3
  tail_min_ratio: 0.001
  random_seed: 42
outlier_filter:
  n_assignments: 6
  sim_metric: wang
  goa_metric: mbl
  random_seed: 42
metrics:
  similarity_methods:
  - resnik
  - lin
  - schlicker
  - wang
  calculate_mbl: true
  force_recalculate: false
logging:
  level: INFO
  log_file: .experiments/runs/20260803_0304_a68aa0bb/pipeline.log
